<?php

namespace Hartenthaler\Webtrees\Module\MetaSearch;

use Fisharebest\Webtrees\I18N;

/**
 * @var string      $database_name
 * @var string      $database_url
 * @var bool        $empty
 * @var array       $hits
 */

?>
<?= e("<result>") ?>
    <?php if ($empty): ?>
        <?= e("<database>") ?>
            <?= e("<name>" . $database_name . "</name>") ?>
            <?= e("<url>" . $database_url . "</url>") ?>
        <?= e("</database>") ?>
    <?php else: ?>
        <?php foreach ($hits as $tree_name => $entries) : ?>
            <?= e("<database>") ?>
                <?= e("<name>" . $database_name . ' - ' . $tree_name . "</name>") ?>
                <?= e("<url>" . $database_url . '/tree=' . $tree_name . "</url>") ?>
                <?php foreach ($entries->entries as $entry) : ?>
                    <?= e("<entry>") ?>
                        <?= e("<lastname>" . $entry->lastname . "</lastname>") ?>
                        <?= e("<firstname>" . $entry->firstname . "</firstname>") ?>
                        <?= e("<details>" . $entry->details . "</details>") ?>
                        <?= e("<url>" . $entry->url . "</url>") ?>
                    <?= e("</entry>") ?>
                <?php endforeach ?>
                <?php if ($entries->more): ?>
                    <?= e("<more>true</more>") ?>
                <?php endif ?>
            <?= e("</database>") ?>
        <?php endforeach ?>
    <?php endif ?>
<?= e("</result>") ?>