<?php

namespace Hartenthaler\Webtrees\Module\MetaSearch;

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Session;
use Fisharebest\Webtrees\Site;
use Fisharebest\Webtrees\View;


/**
 * @var  string		$title
 * @var  string		$description
 * @var  array      $tree_list
 * @var  int		$max_hit
 * @var  string		$secret_key
 * @var  bool		$use_hash
 */
 
/**
 * Soll/kann mit Hash/Key gearbeitet werden?
 * Die zu durchsuchenden Trees müssen einzeln aus/abgewählt werden können; es kommen nur für Gäste sichtbare Trees in Frage.
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?=e($title) ?></h1>
<p><?=e($description) ?></p>

<form method="post">
	<?= csrf_field() ?>
	<input type="hidden" name="save" id="save" value="1">
	<div class="row mb-3 justify-content-between m-0">
		<div class="row mb-3"><?= view('icons/spacer') ?></div> 
		<?php if (!$use_hash) : ?>
			<div class="alert alert-warning">
				<p><?= I18N::translate('Currently, the authorization key is not encrypted. This option is less secure and should only be used in local environments with limited users. Otherwise, please activate encrpytion of the authorization key.') ?></p>
			</div>  
		<?php endif ?>

		<?php if ($secret_key === '') : ?>
			<div class="alert alert-danger">
				<p><?= I18N::translate('The authorization key is empty or not available') ?></p>
			</div>  
		<?php endif ?>

		<h3><?= I18N::translate('Settings for authorization key') ?></h3>			
		<div class="row mb-3">
			<label class="col-sm-3 col-form-label wt-page-options-label" for="secret_key">
				<?= I18N::translate('Current authorization key') ?>
			</label>
			<?php if ($use_hash && ($secret_key !== '')) : ?>
				<?php $text_shown_for_secret_key = I18N::translate('The authorization key cannot be shown, because encryption is activated. If you forgot the key, you have to create a new key.')  ?>
			<?php else : ?>
				<?php $text_shown_for_secret_key = $secret_key  ?>
			<?php endif ?>
			<div class="col-sm-9 wt-page-options-value">
				<input class="form-control" id="secret_key" name="secret_key" type="text" value="<?= e($text_shown_for_secret_key) ?>">
			</div>
		</div>				
		<div class="row mb-3">
			<label class="col-sm-3 col-form-label wt-page-options-label" for="new_secret_key">
				<?= I18N::translate('New authorization key') ?>
			</label>
			<div class="col-sm-9 wt-page-options-value">
				<input class="form-control" id="new_secret_key" name="new_secret_key" type="text">
			</div>
		</div>
		<fieldset class="mb-3">
			<div class="row">
				<legend class="col-form-label col-sm-3">
					<?= I18N::translate('Activate encryption of the authorization key') ?>
				</legend>
				<div class="col-sm-9">
				<?= view('components/checkbox', ['label' => I18N::translate('Activate'), 'name' => MetaSearch::PREF_USE_HASH, 'checked' => $use_hash]) ?>
					<div class="form-text">
						<?= I18N::translate('The encryption of the authorization key is more secure, because the authorization key is not visible to anyone and also encrypted in the database. However, the authorization key is not readible any more (e.g. for other administrators) and cannot be recovered if it is forgotten.'); ?>
					</div>
				</div>
			</div>
		</fieldset>				

		<h3><?= I18N::translate('Select trees to be searched') ?></h3>

		<h3><?= I18N::translate('Define maximum number of hits per tree') ?></h3>
		<div class="row mb-3">
			<label class="col-sm-3 col-form-label wt-page-options-label" for="max_hit">
				<?= I18N::translate('Maximum number of hits (greater or equal 1)') ?>
			</label>
			<div class="col-sm-9 wt-page-options-value">
				<input class="form-control" id="max_hit" name="max_hit" type="int">
			</div>
		</div>
		
		<div class="col">
			<p></p>
			<button type="submit" class="btn btn-primary">
				<?= view('icons/save') ?>
				<?= I18N::translate('Save') ?>
			</button>
		</div>
	</div>
</form>	

<?php View::push('javascript') ?>
<script>
    $('#select-all-1').change(function(e) {
        if (e.currentTarget.checked) {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', true);
        } else {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', false);
        }
    });
</script>
<?php View::endpush() ?>